// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stlimtat/remiges-smtp/internal/crypto (interfaces: IKeyGenerator,IKeyWriter)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=crypto . IKeyGenerator,IKeyWriter
//

// Package crypto is a generated GoMock package.
package crypto

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIKeyGenerator is a mock of IKeyGenerator interface.
type MockIKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIKeyGeneratorMockRecorder
	isgomock struct{}
}

// MockIKeyGeneratorMockRecorder is the mock recorder for MockIKeyGenerator.
type MockIKeyGeneratorMockRecorder struct {
	mock *MockIKeyGenerator
}

// NewMockIKeyGenerator creates a new mock instance.
func NewMockIKeyGenerator(ctrl *gomock.Controller) *MockIKeyGenerator {
	mock := &MockIKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockIKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKeyGenerator) EXPECT() *MockIKeyGeneratorMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockIKeyGenerator) GenerateKey(ctx context.Context, bitSize int, id string) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey", ctx, bitSize, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockIKeyGeneratorMockRecorder) GenerateKey(ctx, bitSize, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockIKeyGenerator)(nil).GenerateKey), ctx, bitSize, id)
}

// MockIKeyWriter is a mock of IKeyWriter interface.
type MockIKeyWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIKeyWriterMockRecorder
	isgomock struct{}
}

// MockIKeyWriterMockRecorder is the mock recorder for MockIKeyWriter.
type MockIKeyWriterMockRecorder struct {
	mock *MockIKeyWriter
}

// NewMockIKeyWriter creates a new mock instance.
func NewMockIKeyWriter(ctrl *gomock.Controller) *MockIKeyWriter {
	mock := &MockIKeyWriter{ctrl: ctrl}
	mock.recorder = &MockIKeyWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKeyWriter) EXPECT() *MockIKeyWriterMockRecorder {
	return m.recorder
}

// WriteKey mocks base method.
func (m *MockIKeyWriter) WriteKey(ctx context.Context, id string, publicKeyPEM, privateKeyPEM []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteKey", ctx, id, publicKeyPEM, privateKeyPEM)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteKey indicates an expected call of WriteKey.
func (mr *MockIKeyWriterMockRecorder) WriteKey(ctx, id, publicKeyPEM, privateKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteKey", reflect.TypeOf((*MockIKeyWriter)(nil).WriteKey), ctx, id, publicKeyPEM, privateKeyPEM)
}
