// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stlimtat/remiges-smtp/internal/file_mail (interfaces: IMailTransformer)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=file_mail . IMailTransformer
//

// Package file_mail is a generated GoMock package.
package file_mail

import (
	context "context"
	reflect "reflect"

	config "github.com/stlimtat/remiges-smtp/internal/config"
	file "github.com/stlimtat/remiges-smtp/internal/file"
	pmail "github.com/stlimtat/remiges-smtp/pkg/pmail"
	gomock "go.uber.org/mock/gomock"
)

// MockIMailTransformer is a mock of IMailTransformer interface.
type MockIMailTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockIMailTransformerMockRecorder
	isgomock struct{}
}

// MockIMailTransformerMockRecorder is the mock recorder for MockIMailTransformer.
type MockIMailTransformerMockRecorder struct {
	mock *MockIMailTransformer
}

// NewMockIMailTransformer creates a new mock instance.
func NewMockIMailTransformer(ctrl *gomock.Controller) *MockIMailTransformer {
	mock := &MockIMailTransformer{ctrl: ctrl}
	mock.recorder = &MockIMailTransformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMailTransformer) EXPECT() *MockIMailTransformerMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockIMailTransformer) Index() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index")
	ret0, _ := ret[0].(int)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockIMailTransformerMockRecorder) Index() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockIMailTransformer)(nil).Index))
}

// Init mocks base method.
func (m *MockIMailTransformer) Init(ctx context.Context, cfg config.FileMailConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockIMailTransformerMockRecorder) Init(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIMailTransformer)(nil).Init), ctx, cfg)
}

// Transform mocks base method.
func (m *MockIMailTransformer) Transform(ctx context.Context, fileInfo *file.FileInfo, myMail *pmail.Mail) (*pmail.Mail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", ctx, fileInfo, myMail)
	ret0, _ := ret[0].(*pmail.Mail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transform indicates an expected call of Transform.
func (mr *MockIMailTransformerMockRecorder) Transform(ctx, fileInfo, myMail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockIMailTransformer)(nil).Transform), ctx, fileInfo, myMail)
}
